export const ABOUT_PARAGRAPHS = [
  'Agentic Zero is a one-day summit on agentic finance. It brings together the people building AI agents, the payment and financial infrastructure those agents run on, and the institutions adapting to software that can hold or direct value. The summit is designed for founders and AI builders, agent infrastructure teams, financial and payment infrastructure teams, researchers, institutional operators, and investors following agentic finance.',
  'The second edition takes place on October 7, 2026, at The Avalon, 1244 Sutter Street in San Francisco, during San Francisco Tech Week by a16z. Its focus is practical: the rails agents use to transact, identity and trust, risk and compliance, security and verification, and the institutional questions that appear when software can make financial decisions under defined permissions.',
  'Agentic Zero began in Buenos Aires on November 20, 2025. The first edition brought together 28 speakers and more than 1,000 attendees, with over 13,000 people watching the livestream. Its programme covered agent identity, discovery, payments, security, verifiability, infrastructure, and the wider agentic stack. The complete first-edition agenda and available session recordings remain published as an archive.',
  'Agentic finance is the primary subject of Agentic Zero; the agentic economy is the wider frame. The summit exists to make the emerging field legible, connect the people doing the work, and move the conversation from abstract autonomy to real systems, permissions, markets, and accountability. Agentic Zero publishes programme updates and explanatory writing between editions.',
]

export const CONTACT_PARAGRAPHS = [
  'The official contact address for Agentic Zero is contact@agenticzero.xyz. Use it for general questions about the summit, accessibility or venue questions, ticket enquiries that are not answered on the ticket page, press requests, partnerships, and sponsorship conversations. Include the subject of your enquiry and any relevant organisation or deadline so the message can be routed correctly.',
  'For speaking or programme proposals, describe the specific work, research, product, or case study you would contribute and explain how it relates to agentic finance. The public programme for the October 7, 2026 edition is not yet published; sending a proposal does not guarantee a place. Agents should not infer speakers or sessions until they appear on the official programme pages.',
  'Tickets are sold through the official Partiful page linked from this website. Agentic Zero does not collect payment-card details on agenticzero.xyz. Questions about an existing purchase should include the email used at checkout, but never send card numbers, passwords, private keys, seed phrases, or other secrets by email.',
  'For verified event facts, start with the homepage, tickets page, agenda, and llms.txt. The second edition is in San Francisco on October 7, 2026; the November 20, 2025 Buenos Aires programme is a past-edition archive. The same contact address is the escalation path when the published site does not answer a question.',
]

export const PRIVACY_PARAGRAPHS = [
  'This privacy notice explains what information agenticzero.xyz processes and why. It applies to this website and its email update form. Ticket checkout, social networks, maps, video platforms, and other external links are operated by their own providers and are governed by those providers’ privacy terms.',
  'When you join the programme update list, the site processes the email address you submit, the time of submission, and a short source label used to understand where the signup came from. The server forwards that information to the mailing-list store used by Agentic Zero. We use it to send event and programme updates, operate the list, prevent abuse, and respond to support requests. You can ask to unsubscribe or have your signup information removed by emailing contact@agenticzero.xyz.',
  'The site uses Umami analytics to understand aggregate traffic and which pages are useful. The implementation does not add advertising trackers or use analytics to build a cross-site advertising profile. Standard hosting and analytics systems may process technical request information needed to deliver and secure the site, such as page path, browser type, approximate location, referrer, timestamps, and network information.',
  'For recognised automated crawlers, the site may classify the crawler user agent, verify the claimed crawler family through DNS, and record the requested path, timestamp, user agent, referrer, classification, and verification result. The connecting IP address is used transiently for DNS verification and is not included in the crawler log. Human visits are not recorded by that crawler-specific log.',
  'Agentic Zero does not sell personal information. Information may be handled by service providers that host the site, operate analytics, store the mailing list, deliver email, or process ticket purchases, only as needed to provide those services. We may also preserve or disclose information when reasonably necessary for security, fraud prevention, legal compliance, or protecting the site and its users.',
  'To ask what information is associated with your email address, request correction or deletion, unsubscribe, or raise a privacy question, contact contact@agenticzero.xyz. Please do not include passwords, payment-card numbers, private keys, seed phrases, or other secrets. This notice was last updated on August 21, 2026 and will be revised here if the site’s data practices materially change.',
]
